channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - scapy
  - pyshark
  - pandas
  - matplotlib
  - requests
  - bs4
  - cryptography
  - numpy
  - openssl
  - scipy
  - beautifulsoup4
